apiVersion: v1
kind: Namespace
metadata:
  name: goldpinger
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: goldpinger
rules:
- apiGroups:
  - ""
  resources:
  - "nodes"
  - "pods"
  verbs:
  - "get"
  - "watch"
  - "list"
---
apiVersion: v1
kind: Service
metadata:
  name: goldpinger
  namespace: goldpinger
  labels:
    k8s-app: goldpinger
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "Goldpinger"
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: ui
  selector:
    k8s-app: goldpinger
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: goldpinger
subjects:
- kind: ServiceAccount
  name: default
  namespace: goldpinger
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: goldpinger
  apiGroup: ""
---
apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: goldpinger
  namespace: goldpinger
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 99%
  selector:
    matchLabels:
      k8s-app: goldpinger
  template:
    metadata:
      labels:
        k8s-app: goldpinger
    spec:
      serviceAccountName: default
      containers:
      - name: goldpinger
        image: ${IMAGE}
        args:
          - -hostName=${DOLLAR}{NODE_NAME}
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        resources:
          limits:
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 80
          name: ui
          protocol: TCP
