apiVersion: v1
kind: Namespace
metadata:
  name: goldpinger-development
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: goldpinger-development
rules:
- apiGroups:
  - ""
  resources:
  - "nodes"
  - "pods"
  verbs:
  - "get"
  - "watch"
  - "list"
---
apiVersion: v1
kind: Service
metadata:
  name: goldpinger
  namespace: goldpinger-development
  labels:
    k8s-app: goldpinger
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "Goldpinger"
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: ui
  selector:
    k8s-app: goldpinger
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: goldpinger-development
subjects:
- kind: ServiceAccount
  name: default
  namespace: goldpinger-development
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: goldpinger-development
  apiGroup: ""
---
apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: goldpinger
  namespace: goldpinger-development
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
  selector:
    matchLabels:
      k8s-app: goldpinger
  template:
    metadata:
      labels:
        k8s-app: goldpinger
    spec:
      serviceAccountName: default
      containers:
      - name: goldpinger
        image: ${IMAGE}
        command:
          - sh
          - -c
          - "/goldpinger -hostName=${DOLLAR}NODE_NAME -namespace=goldpinger-development"
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 80
          name: ui
          protocol: TCP
